image: node:alpine

before_script:
    - export APP_ENV=testing
    - yarn config set registry 'https://registry.npm.taobao.org'

stages:
    - prepare
    - test

variables:
    NPM_CONFIG_CACHE: "/cache/npm"
    YARN_CACHE_FOLDER: "/cache/yarn"
    DOCKER_DRIVER: overlay2
build-cache:
    stage: prepare
    script:
        - yarn install --cache-folder /cache/yarn
    cache:
      key: "$CI_COMMIT_REF_NAME"
      paths:
        - node_modules
    except:
        - docs
        - tags
    when: manual
    tags:
        - mainland
tslint:
    stage: test
    dependencies: []
    cache:
      key: "$CI_COMMIT_REF_NAME"
      policy: pull
      paths:
        - node_modules
    script:
        - if [ ! -d "node_modules" ]; then
        - yarn install --cache-folder /cache/yarn
        - fi
        - yarn tslint -p ./
    except:
        - docs
        - develop
        - master
        - tags
    tags:
        - mainland

unit-test:
    stage: test
    dependencies: []
    artifacts:
        name: "debug"
        when: on_failure
        untracked: false
        expire_in: 60 mins
        paths:
            - $CI_PROJECT_DIR/tests/
    cache:
      key: "$CI_COMMIT_REF_NAME"
      paths:
        - node_modules
    script:
        - if [ ! -d "vendor" ]; then
        - yarn install --cache-folder /cache/yarn
        - fi
        - yarn run test --coverage
    except:
        - docs
    tags:
        - mainland